credentials:
  usernames:
    user:
      email: user@kearney.com
      name: user
      password: $2b$12$Ho9d8AgdOeMj/OQIC/DnsOicHgqtueAct7KTH9dpuJktyTVyaT1Su  # z4O`0+40NjrX

cookie:
  expiry_days: 30
  key: some_signature_key_12345
  name: contract_dashboard_cookie

preauthorized:
  emails:
  - admin@kearney.com